# Generated by Django 3.1.5 on 2021-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBetLotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberLotto', models.IntegerField()),
                ('top', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
